name: job_portal_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  dio: ^5.6.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.0
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/hamburger.png
    - assets/icons/search.png
